c_compiler:
  - clang  # [osx]
cxx_compiler:
  - clangxx  # [osx]
fortran_compiler:
  - gfortran  # [osx]
mpi:
  - 'mpich'
petsc:
  - '3.10.*'
numpy:
  - '1.14.*'
pin_run_as_build:
  eigen:
    max_pin: x.x
  numpy:
    max_pin: x.x
  mpich:
    max_pin: x.x
  petsc:
    max_pin: x.x
  petsc4py:
    max_pin: x.x
  ptscotch:
    max_pin: x.x.x
  slepc:
    max_pin: x.x
  slepc4py:
    max_pin: x.x
