{% set version = "2018.1.0" %}

package:
  name: fenics
  version: {{version}}

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-{{version}}.post0.tar.gz
  sha256: 4644b0f2a64aafa59f8705c7fa0a1825abc05fa59afa504d99d78ab1bb2c127d
  patches:
    - public-eigenlubase.patch  # [osx]

build:
  number: 1004
  skip: true  # [win or py2k]
  run_exports:
    - {{ pin_subpackage('fenics', 'max_pin=x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gcc >=4.8.3  # [linux and c_compiler == 'toolchain_c']
  host:
    - python
    - pip
    - boost
    - cmake >=3.9
    - eigen
    - pkg-config
    - pkgconfig
    - ptscotch
    - zlib
    - {{ mpi }}
    - mpi4py
    - openblas
    - petsc {{ petsc }}
    - petsc4py {{ petsc }}
    - slepc {{ petsc }}
    - slepc4py {{ petsc }}
    - numpy
    - pybind11
    - six
    - sympy >=1,<1.2
    - hdf5

  run:
    - gcc >=4.8.3  # [linux]
    - python
    - setuptools
    - boost
    - cmake >=3.9
    - eigen
    - {{ mpi }}
    - mpi4py
    - openblas
    - petsc
    - petsc4py
    - slepc
    - slepc4py
    - pkg-config
    - pkgconfig  # Python pkgconfig package
    - ptscotch
    - pybind11
    - zlib
    - {{ pin_compatible('numpy', max_pin=None) }}
    - six
    - sympy >=1,<1.2
    - hdf5

test:
  source_files:
    - python/test

  requires:
    - nose
    - pytest
    - git
    - decorator

  imports:
    - dijitso
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - dolfin

  commands:
    - ufl-version
    - ufl2py --help

    - ffc --help

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (<http://fenicsproject.org>). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: http://fenics.readthedocs.io/
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
