{% set version = "2019.1.0" %}

package:
  name: fenics
  version: {{version}}

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-{{version}}.tar.gz
  sha256: 63f8b9475224363faeb3a1e22c12143c20c800e41a40a6d5fd441a573a897e4d

build:
  number: 0
  skip: true  # [win or py2k]
  run_exports:
    - {{ pin_subpackage('fenics', 'max_pin=x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # for applying fiat patch
  host:
    - libblas
    - libcblas
    - python
    - pip
    - boost-cpp
    - cmake >=3.9
    - eigen
    - pkg-config
    - pkgconfig
    - ptscotch
    - zlib
    - {{ mpi }}
    - mpi4py
    - petsc {{ petsc }}
    - petsc4py {{ petsc }}
    - slepc {{ petsc }}
    - slepc4py {{ petsc }}
    - numpy
    - pybind11
    - six
    - sympy >=1
    - hdf5 1.10.4 mpi_{{ mpi }}_*

  run:
    - {{ compiler('cxx') }}  # [linux]
    - python
    - setuptools
    - boost-cpp
    - cmake >=3.9
    - eigen
    - {{ mpi }}
    - mpi4py
    - petsc
    - petsc4py
    - slepc
    - slepc4py
    - pkg-config
    - pkgconfig  # Python pkgconfig package
    - ptscotch
    - pybind11
    - zlib
    - {{ pin_compatible('numpy', max_pin=None) }}
    - six
    - sympy >=1
    - hdf5

test:
  source_files:
    - python/test

  requires:
    - nose
    - pytest
    - git
    - decorator

  imports:
    - dijitso
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - dolfin

  commands:
    - ufl-version
    - ufl2py --help

    - ffc --help

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (<http://fenicsproject.org>). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: http://fenics.readthedocs.io/
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
