# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UM7Mm4KTgjWlqN1PbUDVdOhGlGJGM3qSHfR1MUSjI+eqXXG1HUYbboTok7F/JTE3VUN53HiwBNJXVP2XvE/kCXJGYI13biWkx4+umlmYmq5qZwDMDD7RwNKhrl2vYO9FdcV3F/q5aWBn0bDkKc4XZVxIixkcrhUws383Bv4gXh/yiYi0lnTFCzvfCpjl4YCO4eGwXPGPPubtoLi/sbDyz2fNY/jaylIPzfM8mWLhQ9jvC5qVJERtb3iNJl8/CFkVwaKRecUU38LCRowX9pBmYA1mTvCuAqo+BhEJRMV7H62HdUtNLdj1Z/rlIc6etX92dB2+ISUVxE8kNPWrzsNpGR1tW6hVkwkXVcCpLO+wNDhboafGQNgB/OYWULZHOxJgGVmsdnPdCBB9mUZyj+DF0YJi9IenU+ocKKZSmq4AaqwMIgtfstaykn3ae0s6Xls6KNyklH/nJtGEn0tmain9QM2SBsRFVO2dCCJ9KF3C9cEWPiEh7gEe5gYATTkrMpOhseK3ZkZBh3efodgXpMnbKMILv/ymNfC2+CSQtN0Audc7SdvEiXKwI8sMwY0UsUCCxbVntqX45dv2ZsJHO7mHC8Y9TT6UIm1Swpkjle97Ap108P3HHnFs+6szvtLbUvenAL2gzJ9dItHBZJPyJRaYCBWyEhQuR62VqgekpfOdKgE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
