travis:
  secure:
    BINSTAR_TOKEN: ew7zophridgjakQQypExDggv4U7YuXaT0DcIaSfFnlEUNq3g7DSbM31RrofM5iljHSZGiJ5s9n6r8PdqP7uHNqBYIs5L47KhJjoocHJgXgKgk0ybqhe0Yd5+UjmraHal1lJ9/t1V0oZbr44HIrSYzxbF+80gqGQRsBr2h63zXgoeAseBFVsU+VOtRa7XV0r+T+jy18UYmYF6GVmz/Ll00SGF41EkmdLXFOfraRnzza0CbL9EZzCdA1NtC3s+e7DYZgu1JuCwZiIMSu2d0C8Q6JW1XLuV+2SO4PiCR/2UNF25tgTNK/Cmbr2Bxxxl0Tye8zSK0Ru1AZTz26sJxeQtdAx6EFnyxU3tdVYcNUXGq81CStxO4YQlVjlpPe97LOl94oAqW37UF3EH/0lEUAiiZ52hlocNcd/qeUGqhCxLszY5Y8Bqeytbf7zM/eJ69hlFMMqXXX7Hzw37x+00zq7qPtR4+RlFtZSsMcwHjcjWa3e/Wt60pEitrcbGbXp3FcvfMGUe5YPOxzVEhE+nlE3R0NuK/IKYm7P7Jl9D15zSzgmQPmbPwU+FFFuarZ0rugZwihpeIjaGaMLpGf8LvQZf/jPUAuR6mlWcnC7Lu6yg6zUoZ9Zs+PnjQEJ6V6UuIgNRAcNlF67iV/kdEiQz7hMEpro8VpWTBegyPhVaDeYN2+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
